### ISSUE TITLE
License

### ISSUE THREAD

**Issue by amarrella** [underscoreio/underscore-ebook-template#18]
Hi, I wanted to use this software because I really like your books and wanted to try to write one myself but there is an issue with the license and I don't wanna incur in legal problems :)

In the readme you specify that the software is released under `Apache License 2.2` which doesn't exist. Do you mean `2.0`?

Also, the license file is empty.

Thanks in advance!

**Comment by noelwelsh** [comment]
Yes, I think we meant Apache 2.0.

**Comment by davegurnell** [comment]
Yep. It’s a typo!
