### ISSUE TITLE
Peer Dependencies changing in NPM 3

### ISSUE THREAD

**Issue by noelwelsh** [underscoreio/underscore-ebook-template#8]
@charlottefranklin reported that `peerDependencies` are changing in NPM 3, and this breaks their use in the template. To quote the manual:

> NOTE: npm versions 1 and 2 will automatically install peerDependencies if they are not explicitly  depended upon higher in the dependency tree. In the next major version of npm (npm@3), this will no longer be the case. You will receive a warning that the peerDependency is not installed instead. 

https://docs.npmjs.com/files/package.json

**Comment by c-franklin** [comment]
This can be resolved by moving items in `peerDependencies` to `devDependencies` in `package.json`
